#markdown: rdiscount
highlighter: pygments
markdown: kramdown
permalink: /:year/:month/:day/:title.html
name: "rusty shutter"

author: "bhunix"
atom-baseurl: "bhunix.github.com"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: bhunix.github.com
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

